name: Bug Report Form
description: If something isn't working as expected
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Current Behaviour
      description: A clear and concise description of the buggy behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: >-
        A clear and concise description of what you expected to happen (or
        code).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: Steps to reproduce if any.
      placeholder: Steps to reproduce bug.
      value: |-
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Testing Environment (if applicable)
      description: Steps to reproduce if any.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context/Screenshots
      description: >-
        Add any other context about the problem here. If applicable, add
        screenshots to help explain.
    validations:
      required: true
  - type: input
    attributes:
      label: Estimated time in hours
      description: Enter the estimated time required to finish this task.
      placeholder: 40 Hours
